### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by Lemonadez** [WiNiFiX/LuaUnlocker#1]
Tried 2 Legion private server.

WoW.exe (7.3.5)
WoW.exe (7.2.5)

Both getting 
http://tinyimg.io/i/Iukvhet.png

I also tried going Windows 7/8. Its the same.

**Comment by WiNiFiX** [comment]
Official only, not designed for Private, can't offer support on that.

**Comment by Lemonadez** [comment]
What versions of WoW does it support?
- Versions 7.XX - (Private Servers)
- Versions 8.XX - (Live & Private servers)
- Versions 1.13 - (Classic Beta)
