### ISSUE TITLE
work on my win10 home laptop but not on my win10 pro desktop

### ISSUE THREAD

**Issue by rogerc66** [WiNiFiX/LuaUnlocker#2]
It's strange, it works perfectly on my win10 home edition laptop, however, it doesnt work on my desktop with win10 pro.

Both pop success buttons.

Any idea?

**Comment by rogerc66** [comment]
and i tried disable windows memory protection and core isolation but no luck.

**Comment by rogerc66** [comment]
my .net frame work is up to date at 4.8, is there anything i miss?

**Comment by WiNiFiX** [comment]
Some windows security setting somewhere is enabled, easyist fix is to do fresh install of windows as I have always seen it work on that.
