### ISSUE TITLE
plz , update

### ISSUE THREAD

**Issue by x91270** [WiNiFiX/LuaUnlocker#3]
Hi bro
Can you update the latest version of Classic

**Comment by WiNiFiX** [comment]
Rename WowClassic to Wow.exe and run it, problem solved.
I will update it to support the new WowClassic name though, but the above is a temp solution.

**Comment by WiNiFiX** [comment]
Updated see https://github.com/WiNiFiX/LuaUnlocker/releases/tag/3.0
