### ISSUE TITLE
not working, update or delete...

### ISSUE THREAD

**Issue by Kartonfalter101** [WiNiFiX/LuaUnlocker#4]

**Comment by WiNiFiX** [comment]
So descriptive, whats not working, and since when?

**Comment by Kartonfalter101** [comment]
cant use any protected methods (/script JumpOrAscendStart() for example) after executing your application... Is it still working work u?

**Comment by WiNiFiX** [comment]
Yes, just updated it now for Classic as that had a rename of the EXE, but all still works fine.

**Comment by Kartonfalter101** [comment]
got any idea why it doesnt work for me for retail? this project would really help me out...

**Comment by Kartonfalter101** [comment]
just uploaded a video: https://www.youtube.com/watch?v=W78Tqu_mgtw&

**Comment by donque** [comment]
When I click the unlock button, it tip run success, but it doesn't work. My os version is win10 1903 (18362.535),  wow client is classic,language is simplified Chinese.

**Comment by donque** [comment]
maybe the client's signature is different! can you publish the steps of how to find signatures with CE?thanks

**Comment by Kartonfalter101** [comment]
the success message box has nothing to do with the functionality unlocked by the code injection.

@WiNiFiX can you send us your Wow.exe ? It must be a difference between those .exe files, I can send u mine too, just give me a feedback...

**Comment by WiNiFiX** [comment]
> 
> 
> maybe the client's signature is different! can you publish the steps of how to find signatures with CE?thanks

https://github.com/WiNiFiX/LuaUnlocker/blob/master/Application/Form1.cs#L20 contains the signature, just look at the c# code as you need to look a few bytes forward / backward

**Comment by WiNiFiX** [comment]
My exe's classic and live
https://www.dropbox.com/sh/6zu2j5g57eqagji/AAB1k7ztSBVb2c1Zeuu2kEg9a?dl=0

**Comment by WiNiFiX** [comment]
Look at https://github.com/WiNiFiX/SkyEngine its the same method, but without injecting assembler, it runs out of process, see the sample lua addon to use it.

**Comment by CloakAndDagger-sys** [comment]
Have you heard about Vitalic Elite Rogue? I would die to get my hands on that type of a pvp bot :D i reached gladiator with that bot. Winifix do you have any idea on how he made it?
